In [1]:
import numpy as np
import matplotlib.pyplot as plt 

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, LSTM

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [2]:
sentences = [
    "I am the best version of myself",
    "I hate onions of all kinds",
    "This is the sample text data."
]

In [4]:
MAX_VOCAB_SIZE = 20000
tokenizer = Tokenizer(num_words = MAX_VOCAB_SIZE)
tokenizer.fit_on_texts(sentences)
sequences = tokenizer.texts_to_sequences(sentences)

In [5]:
sequences

[[1, 4, 2, 5, 6, 3, 7], [1, 8, 9, 3, 10, 11], [12, 13, 2, 14, 15, 16]]

In [6]:
tokenizer.word_index

{'i': 1,
 'the': 2,
 'of': 3,
 'am': 4,
 'best': 5,
 'version': 6,
 'myself': 7,
 'hate': 8,
 'onions': 9,
 'all': 10,
 'kinds': 11,
 'this': 12,
 'is': 13,
 'sample': 14,
 'text': 15,
 'data': 16}

In [7]:
len(tokenizer.word_index)

16

In [19]:
data = pad_sequences(sequences , padding = 'post' , maxlen = 4 ,  truncating = 'pre')
data

array([[ 5,  6,  3,  7],
       [ 9,  3, 10, 11],
       [ 2, 14, 15, 16]])

In [21]:
data = pad_sequences(sequences , padding = 'pre' , maxlen = 10 ,  truncating = 'pre')
data

array([[ 0,  0,  0,  1,  4,  2,  5,  6,  3,  7],
       [ 0,  0,  0,  0,  1,  8,  9,  3, 10, 11],
       [ 0,  0,  0,  0, 12, 13,  2, 14, 15, 16]])

In [18]:
data = pad_sequences(sequences , padding = 'post' ,  truncating = 'pre')
data

array([[ 1,  4,  2,  5,  6,  3,  7],
       [ 1,  8,  9,  3, 10, 11,  0],
       [12, 13,  2, 14, 15, 16,  0]])